"""
200 publicly documented conspiracy theories / conspiracy-adjacent topics,
tagged with a tier:

  tier 3 = mainstream / pop-culture famous (safe for broadest audience)
  tier 2 = moderately fringe, still widely written about (mid access)
  tier 1 = deep-cut / historically "darker" but still real, documented,
           non-extremist topics (declassified programs, alleged cover-ups,
           unsolved-death theories, etc.)

Note: deliberately excludes hate-speech-based conspiracies (antisemitic
tropes, Holocaust denial, "great replacement", etc.) and anything that
functions as a call to violence. Those are not included at ANY tier,
regardless of how "extreme" the tier framing wants to go.
"""

THEORIES = [
    # ---------- TIER 3: mainstream / pop-culture ----------
    ("Moon Landing Hoax", "Claim NASA faked the 1969 Moon landings on a soundstage.", 3, "space"),
    ("Flat Earth", "Belief that Earth is a flat disc, not a sphere.", 3, "science"),
    ("Area 51 / Aliens", "Belief the Nevada base hides crashed UFOs or alien tech.", 3, "ufo"),
    ("Roswell Incident", "1947 New Mexico crash allegedly covered up as an alien craft.", 3, "ufo"),
    ("Loch Ness Monster", "Belief a large unknown creature lives in Loch Ness, Scotland.", 3, "cryptid"),
    ("Bigfoot / Sasquatch", "Belief in a large undocumented ape-like creature in North America.", 3, "cryptid"),
    ("Bermuda Triangle", "Claim an area of the Atlantic causes unexplained ship/plane disappearances.", 3, "mystery"),
    ("Paul Is Dead", "1960s rumor that Paul McCartney died and was replaced by a lookalike.", 3, "pop-culture"),
    ("Denver Airport Conspiracy", "Claim DIA's murals and layout hint at a secret elite bunker.", 3, "landmark"),
    ("Mandela Effect", "Large groups sharing the same false memory of past events.", 3, "psychology"),
    ("Illuminati Controls Pop Music", "Claim a secret elite uses celebrities to spread hidden messages.", 3, "celebrity"),
    ("Reptilian Elite", "Belief that shape-shifting reptilian beings secretly rule the world.", 3, "ufo"),
    ("Chemtrails", "Belief that aircraft contrails are chemical agents sprayed deliberately.", 3, "environment"),
    ("Birds Aren't Real", "Satirical (now semi-serious) claim birds are government surveillance drones.", 3, "internet"),
    ("Stanley Kubrick Filmed the Moon Landing", "Claim the director secretly staged NASA's footage.", 3, "space"),
    ("Elvis Is Alive", "Claim Elvis Presley faked his 1977 death.", 3, "celebrity"),
    ("Tupac Is Alive", "Claim the rapper survived his 1996 shooting and is in hiding.", 3, "celebrity"),
    ("Avril Lavigne Replaced", "Internet rumor the singer died and was replaced by a body double.", 3, "celebrity"),
    ("Katy Perry is JonBenét Ramsey", "Internet rumor claiming the singer is the grown-up JonBenét.", 3, "celebrity"),
    ("Finland Doesn't Exist", "Joke theory claiming Finland is a fabricated landmass.", 3, "geography"),
    ("Australia Doesn't Exist", "Joke theory claiming Australia is a British-run fabrication.", 3, "geography"),
    ("The Simpsons Predicts the Future", "Claim the show has repeatedly predicted real events.", 3, "pop-culture"),
    ("Time Travelers Caught on Film", "Various viral photos claimed to show time travelers.", 3, "internet"),
    ("Fiji Water Girl Illuminati Signal", "Viral claim a 2019 photobomb was a coded message.", 3, "internet"),
    ("Big Foot DNA Cover-Up", "Claim scientific institutions suppress Bigfoot DNA evidence.", 3, "cryptid"),
    ("Nessie Government Cover-Up", "Claim the UK government hides proof of the Loch Ness Monster.", 3, "cryptid"),
    ("Hollow Earth", "Belief the Earth is hollow and inhabited internally.", 3, "science"),
    ("Ancient Aliens Built the Pyramids", "Claim extraterrestrials helped construct ancient monuments.", 3, "history"),
    ("Atlantis Is Real", "Belief a lost advanced civilization sank beneath the ocean.", 3, "history"),
    ("Yeti Cover-Up", "Claim governments hide evidence of the Himalayan Yeti.", 3, "cryptid"),
    ("5G Causes Illness", "Unfounded claim 5G networks cause health problems.", 3, "technology"),
    ("Fluoride Mind Control", "Claim water fluoridation is used to pacify the population.", 3, "health"),
    ("HAARP Weather Control", "Claim a research facility secretly controls global weather.", 3, "science"),
    ("Phantom Time Hypothesis", "Claim ~300 years of the early medieval calendar were fabricated.", 3, "history"),
    ("Dinosaurs Never Existed", "Fringe claim dinosaur fossils are a fabricated hoax.", 3, "science"),
    ("The Earth Is Actually Expanding", "Fringe geophysics theory rejecting plate tectonics.", 3, "science"),
    ("NASA Faked Mars Rover Photos", "Claim Mars mission imagery is staged on Earth.", 3, "space"),
    ("Shakespeare Didn't Write Shakespeare", "Authorship theory crediting someone else with the plays.", 3, "history"),
    ("Disney World Cryogenics", "Urban legend Walt Disney's body is frozen beneath the park.", 3, "celebrity"),
    ("Coca-Cola Original Formula Conspiracy", "Claim the 'secret formula' story is corporate marketing myth.", 3, "corporate"),
    ("Nike Swoosh Subliminal Messaging", "Claim consumer brand logos hide subliminal cues.", 3, "corporate"),

    # ---------- TIER 2: moderately fringe, well documented ----------
    ("New World Order", "Belief a secretive elite plans a unified authoritarian global government.", 2, "politics"),
    ("Bilderberg Group Control", "Claim the annual private conference secretly steers world policy.", 2, "politics"),
    ("QAnon Movement", "Modern US movement alleging a hidden elite cabal fought by a secret insider.", 2, "politics"),
    ("Deep State", "Belief an unelected permanent bureaucracy secretly runs government policy.", 2, "politics"),
    ("Federal Reserve Secret Owners", "Claim the US central bank is privately controlled for elite benefit.", 2, "finance"),
    ("Agenda 21 / 2030", "Claim UN sustainability plans are cover for global population control.", 2, "politics"),
    ("Georgia Guidestones Message", "Debate over the meaning of the now-demolished monument's inscriptions.", 2, "monument"),
    ("Vaccine Microchips", "Unfounded claim vaccines implant tracking microchips.", 2, "health"),
    ("Moon Landing Faked to Beat USSR", "Cold War-motivated variant of the Moon hoax claim.", 2, "space"),
    ("Big Pharma Suppresses Cancer Cure", "Claim a cure exists but is hidden for profit.", 2, "health"),
    ("Planned Obsolescence Conspiracy", "Claim manufacturers secretly design products to fail early.", 2, "corporate"),
    ("Weather Modification for War", "Claim militaries use engineered weather as a weapon.", 2, "military"),
    ("Denver Airport Illuminati Base", "Extended version of the DIA theory alleging an underground elite city.", 2, "landmark"),
    ("Club of Rome Depopulation Plan", "Claim the think tank secretly pushes population reduction policy.", 2, "politics"),
    ("World Economic Forum 'Great Reset'", "Claim the WEF is executing a covert global economic takeover.", 2, "politics"),
    ("9/11 Controlled Demolition", "Claim the WTC towers were brought down by planted explosives, not the planes.", 2, "history"),
    ("Pearl Harbor Foreknowledge", "Claim FDR knew of the attack in advance and allowed it.", 2, "history"),
    ("JFK Assassination — Multiple Shooters", "Theory alleging more than one gunman killed JFK in 1963.", 2, "history"),
    ("CIA and the Crack Epidemic", "Alleged CIA tolerance of cocaine trafficking during the Contra war.", 2, "history"),
    ("Vaccine-Autism Link", "Long-debunked claim linking childhood vaccines to autism.", 2, "health"),
    ("AIDS Created in a Lab", "Claim HIV/AIDS was deliberately engineered as a bioweapon.", 2, "health"),
    ("Y2K Was a Banking Scam", "Claim the Y2K bug was exaggerated to justify tech/consulting spending.", 2, "technology"),
    ("Big Oil Suppressed Electric Cars", "Claim early EV technology was bought out and shelved.", 2, "corporate"),
    ("Diamond Cartel Price Fixing", "Claim De Beers artificially manufactured diamond scarcity and demand.", 2, "corporate"),
    ("Sugar Industry Hid Health Research", "Documented mid-20th-century sugar lobby funding of favorable studies.", 2, "health"),
    ("Tobacco Industry Cover-Up", "Documented decades-long suppression of smoking-cancer research.", 2, "health"),
    ("Bohemian Grove Secret Rituals", "Claim elite attendees at the California retreat perform occult rites.", 2, "elite"),
    ("Skull and Bones Society", "Claim the Yale secret society shapes US political power behind the scenes.", 2, "elite"),
    ("Freemasons Run the World", "Claim the fraternal order secretly directs global affairs.", 2, "elite"),
    ("Rothschild Family World Control", "Claim the banking family secretly controls global finance.", 2, "finance"),
    ("Rockefeller Medicine Conspiracy", "Claim the Rockefeller family suppressed alternative medicine for profit.", 2, "health"),
    ("Fake Moon Landing Photography Errors", "Claim inconsistent shadows/lighting in NASA photos prove a hoax.", 2, "space"),
    ("Election Fraud Machines", "Recurring claims that voting machines are rigged to alter results.", 2, "politics"),
    ("False Flag Mass Shootings", "Claim certain shootings were staged to justify gun-control laws.", 2, "politics"),
    ("Sandy Hook Was Staged", "Claim the 2012 school shooting was fabricated with actors.", 2, "politics"),
    ("Boston Marathon Bombing Staged", "Claim the 2013 bombing involved 'crisis actors'.", 2, "politics"),
    ("Bilderberg Selects World Leaders", "Claim the group pre-selects future heads of state.", 2, "politics"),
    ("Illuminati Founded the US", "Claim Enlightenment-era secret society founded America's institutions.", 2, "history"),
    ("Pizzagate", "2016 false claim tying a DC pizzeria to a child-trafficking ring.", 2, "politics"),
    ("Chemtrail Population Control", "Extended chemtrail claim alleging deliberate mass sterilization.", 2, "environment"),
    ("Big Tech Shadow Banning", "Claim platforms secretly suppress certain users' visibility.", 2, "technology"),
    ("Smart Meters Spy on Homes", "Claim utility smart meters are used for covert surveillance.", 2, "technology"),
    ("Moon Landing Radiation Impossibility", "Claim Van Allen belt radiation would have killed the astronauts.", 2, "space"),
    ("Denver Airport Reptilian Sculptures", "Claim airport artwork encodes reptilian-elite symbolism.", 2, "landmark"),
    ("Antarctic Treaty Cover-Up", "Claim the treaty hides ancient ruins or crashed craft beneath the ice.", 2, "geography"),
    ("Nazi Bell Project", "Claim Nazi Germany secretly developed advanced anti-gravity tech.", 2, "history"),
    ("Operation Paperclip Suppression", "Claim the extent of recruited Nazi scientists remains hidden today.", 2, "history"),
    ("Nikola Tesla's Suppressed Inventions", "Claim free-energy technology was buried by industrial interests.", 2, "technology"),
    ("Bilderberg and Cashless Society Plan", "Claim elites are engineering a global cashless surveillance economy.", 2, "finance"),
    ("Federal Reserve Engineered the Depression", "Claim the 1929 crash was deliberately orchestrated by bankers.", 2, "finance"),

    # ---------- TIER 1: darker / deep-cut, still real & documented ----------
    ("MKUltra", "Real, declassified 1950s–70s CIA mind-control experiments on unwitting subjects.", 1, "government"),
    ("Operation Northwoods", "Declassified 1962 Pentagon plan for staged attacks to justify war with Cuba.", 1, "government"),
    ("Operation Mockingbird", "Alleged Cold War-era CIA program to secretly influence US media outlets.", 1, "government"),
    ("Tuskegee Syphilis Study", "Real 40-year US government study that withheld treatment from Black men.", 1, "government"),
    ("COINTELPRO", "Real FBI covert program (1956–71) that surveilled and disrupted domestic groups.", 1, "government"),
    ("Gulf of Tonkin Incident", "Disputed 1964 naval incident used to justify escalating the Vietnam War.", 1, "government"),
    ("Iran-Contra Affair", "Real 1980s US scandal covertly funding rebels via secret arms sales.", 1, "government"),
    ("CIA Assassination Manuals", "Declassified CIA field manuals on covert assassination methods.", 1, "government"),
    ("Project MKNAOMI", "Declassified CIA program researching biological and chemical weapons materials.", 1, "government"),
    ("Church Committee Revelations", "1975 Senate probe exposing widespread illegal US intelligence abuses.", 1, "government"),
    ("Jeffrey Epstein Client List", "Ongoing speculation over undisclosed names tied to Epstein's network.", 1, "elite"),
    ("Epstein 'Suicide' Doubts", "Persistent claims Epstein's 2019 death in custody was not a suicide.", 1, "elite"),
    ("JFK Jr. Plane Crash Theories", "Claims the 1999 crash that killed JFK Jr. was not an accident.", 1, "history"),
    ("Marilyn Monroe Murder Theory", "Claim the actress's 1962 death was a Kennedy-linked cover-up, not suicide.", 1, "history"),
    ("Princess Diana Assassination", "Claim the 1997 Paris crash was an orchestrated hit, not an accident.", 1, "history"),
    ("MLK Assassination Conspiracy", "Claims of broader government involvement beyond the convicted shooter.", 1, "history"),
    ("RFK Assassination — Second Gunman", "Theory alleging a second shooter beyond Sirhan Sirhan in 1968.", 1, "history"),
    ("Business Plot of 1933", "Real alleged Wall Street plot to overthrow FDR, per Congressional testimony.", 1, "history"),
    ("Waco Siege Government Overreach", "Claims federal agents deliberately escalated the fatal 1993 standoff.", 1, "government"),
    ("Ruby Ridge Cover-Up", "Claims of a federal cover-up after the fatal 1992 standoff in Idaho.", 1, "government"),
    ("Project SUNSHINE", "Declassified Cold War program studying secretly-obtained human remains for radiation data.", 1, "government"),
    ("Human Radiation Experiments", "Real Cold War-era US experiments exposing unwitting citizens to radiation.", 1, "government"),
    ("CIA Drug Trafficking in Southeast Asia", "Alleged CIA-linked opium trafficking during the Vietnam War era.", 1, "government"),
    ("School of the Americas", "Real US military training program linked to Latin American human-rights abuses.", 1, "government"),
    ("Operation Gladio", "Real Cold War NATO 'stay-behind' network linked to European false-flag violence claims.", 1, "government"),
    ("Dyatlov Pass Incident", "Unsolved 1959 deaths of Soviet hikers, with cover-up theories persisting.", 1, "mystery"),
    ("D.B. Cooper Government Silence", "Claim authorities know more than disclosed about the unsolved 1971 hijacking.", 1, "mystery"),
    ("Georgia Guidestones Bombing Cover-Up", "Speculation over who destroyed the monument in 2022 and why.", 1, "monument"),
    ("Havana Syndrome", "Unexplained illnesses among diplomats, with theories of a covert directed-energy attack.", 1, "government"),
    ("USS Liberty Incident", "Claims the 1967 attack on a US ship was a deliberate cover-up, not friendly-fire error.", 1, "military"),
    ("MH370 Disappearance Cover-Up", "Claims governments know more than disclosed about the 2014 vanished flight.", 1, "mystery"),
    ("Denver Airport Underground Base (Extended)", "Fullest version alleging a hidden bunker city beneath DIA for elites.", 1, "landmark"),
    ("Bilderberg Shadow Government", "Strongest version alleging the group is an actual ruling shadow government.", 1, "politics"),
    ("Vatican Bank Scandals", "Real historical financial scandals and unexplained deaths tied to Vatican finances.", 1, "elite"),
    ("Roberto Calvi 'Suicide'", "Claim the 1982 death of 'God's Banker' was a mob/Vatican-linked murder staged as suicide.", 1, "elite"),
    ("Jonestown Government Involvement", "Fringe claims of undisclosed US intelligence links to the 1978 mass deaths.", 1, "history"),
    ("Montauk Project", "Claim a secret Long Island facility conducted time-travel/mind-control experiments.", 1, "government"),
    ("Philadelphia Experiment", "Claim a 1943 Navy experiment made a ship invisible and teleported it.", 1, "military"),
    ("Bilderberg Vaccine Depopulation Plan", "Extended claim tying elite meetings directly to population-reduction vaccines.", 1, "health"),
    ("Illuminati Blood Sacrifice Rituals", "Extreme unfounded claim elites perform ritual sacrifices for power.", 1, "elite"),
    ("Denver Airport Doomsday Bunker", "Claim DIA was built as a survival bunker for the ultra-wealthy.", 1, "landmark"),
]

# pad list up toward 200 with additional real, documented but lower-profile entries
EXTRA = [
    ("Bilderberg Predicts Recessions", "Claim attendee timing correlates with engineered market downturns.", 2, "finance"),
    ("Big Sugar Funded Heart Disease Research", "Documented industry funding shaping 1960s dietary-fat science.", 2, "health"),
    ("Opioid Crisis Manufactured Demand", "Documented pharma marketing practices behind US opioid overprescription.", 2, "health"),
    ("Enron Accounting Conspiracy", "Real corporate fraud conspiracy that collapsed the energy giant in 2001.", 2, "corporate"),
    ("Volkswagen Emissions Cover-Up", "Real 2015 conspiracy to fake diesel emissions test results.", 2, "corporate"),
    ("Theranos Fraud", "Real conspiracy to fake blood-testing technology capabilities.", 2, "corporate"),
    ("FIFA Bribery Scandal", "Real conspiracy among officials to rig World Cup host bidding.", 2, "sports"),
    ("Lance Armstrong Doping Cover-Up", "Real conspiracy to conceal systematic doping across a cycling team.", 2, "sports"),
    ("BALCO Doping Scandal", "Real conspiracy supplying undetectable steroids to elite US athletes.", 2, "sports"),
    ("MLB Steroid Era Cover-Up", "Alleged league-wide tolerance of steroid use through the 1990s–2000s.", 2, "sports"),
    ("Watergate Break-In", "Real 1972 conspiracy and cover-up that brought down a US president.", 1, "government"),
    ("Panama Papers Network", "Real leaked documents exposing a global offshore tax-evasion network.", 1, "finance"),
    ("Paradise Papers Network", "Real leaked documents on further offshore wealth concealment.", 1, "finance"),
    ("Libor Rate-Rigging Scandal", "Real conspiracy among major banks to manipulate global interest rates.", 1, "finance"),
    ("Wirecard Accounting Fraud", "Real conspiracy fabricating billions in fictitious company assets.", 1, "corporate"),
    ("1MDB Malaysian Fund Scandal", "Real conspiracy embezzling billions from a state investment fund.", 1, "finance"),
    ("Bofors Arms Deal Scandal", "Real Cold War-era kickback conspiracy in an India-Sweden arms deal.", 1, "government"),
    ("Iran-Contra Arms-for-Hostages", "Real covert deal trading arms for hostages, funding rebels illegally.", 1, "government"),
    ("Cambridge Analytica Data Scandal", "Real conspiracy to harvest and misuse social media data for political targeting.", 1, "technology"),
    ("Stuxnet Origins Cover-Up", "Alleged undisclosed state involvement behind the Stuxnet cyberweapon.", 1, "technology"),
    ("Havana Syndrome Directed Energy Weapon", "Extended theory a hostile state used a covert weapon on diplomats.", 1, "government"),
    ("Antarctic Nazi Base", "Claim a secret Nazi installation survived in Antarctica after WWII.", 1, "history"),
    ("Hitler Escaped to Argentina", "Claim Hitler survived WWII and fled to South America.", 2, "history"),
    ("D-Day Double Agents", "Real WWII conspiracy of Allied double agents feeding false intel to Germany.", 1, "military"),
    ("Enigma Code-Breaking Cover-Up", "Real decades-long secrecy around Allied cryptography successes in WWII.", 1, "military"),
    ("Manhattan Project Secrecy", "Real wartime conspiracy to conceal atomic bomb development.", 1, "government"),
    ("Los Alamos Spy Ring", "Real conspiracy of atomic scientists passing US nuclear secrets to the USSR.", 1, "government"),
    ("Kim Philby / Cambridge Five", "Real Cold War spy ring of British officials working for the USSR.", 1, "government"),
    ("U-2 Incident Cover-Up", "Real 1960 US attempt to conceal a spy plane's true mission after being shot down.", 1, "government"),
    ("Bay of Pigs Planning Failures", "Real covert CIA-planned invasion of Cuba that collapsed in 1961.", 1, "government"),
    ("Nayirah Testimony Hoax", "Real 1990 PR-firm-orchestrated fake testimony used to build support for the Gulf War.", 1, "government"),
    ("WMD Iraq Intelligence Failure", "Claims the 2003 Iraq War case was built on knowingly false intelligence.", 1, "government"),
    ("Snowden NSA Mass Surveillance", "Real 2013 revelations of covert global surveillance programs.", 1, "government"),
    ("Facebook Emotional Contagion Study", "Real covert experiment manipulating users' news feeds without consent.", 2, "technology"),
    ("Google Search Result Manipulation", "Claim search rankings are secretly tuned to favor political outcomes.", 2, "technology"),
    ("Big Tech Antitrust Collusion", "Claim major tech firms secretly coordinate to suppress competitors.", 2, "technology"),
    ("Apple Planned Obsolescence Lawsuit", "Real case where Apple admitted throttling older iPhones.", 2, "corporate"),
    ("Diesel-gate Extended EU Cover-Up", "Claim European regulators knew of emissions cheating for years.", 2, "corporate"),
    ("Purdue Pharma Opioid Conspiracy", "Real conspiracy to downplay OxyContin's addiction risks.", 1, "health"),
    ("Johnson & Johnson Talc Cover-Up", "Real conspiracy allegations over concealed asbestos-contamination data.", 1, "health"),
    ("Big Tobacco 'Doubt Is Our Product' Memo", "Real internal strategy memo revealing deliberate science-doubt campaigns.", 1, "health"),
    ("Exxon Climate Change Cover-Up", "Real internal research showing early climate-change knowledge was suppressed.", 1, "environment"),
    ("Flint Water Crisis Cover-Up", "Real conspiracy by officials to conceal lead contamination in city water.", 1, "government"),
    ("DuPont PFAS Cover-Up", "Real decades-long concealment of 'forever chemical' health risks.", 1, "environment"),
    ("Bhopal Disaster Cover-Up", "Real allegations Union Carbide concealed safety risks before the 1984 gas leak.", 1, "environment"),
    ("Chernobyl Soviet Cover-Up", "Real Soviet-era suppression of the true scale of the 1986 nuclear disaster.", 1, "government"),
    ("Fukushima Data Concealment", "Claims regulators understated the 2011 nuclear disaster's severity.", 2, "environment"),
    ("Nord Stream Pipeline Sabotage", "Disputed 2022 sabotage of undersea gas pipelines, with unresolved state blame.", 1, "geopolitics"),
    ("Skripal Poisoning Cover-Up", "Disputed 2018 nerve-agent poisoning case with competing state narratives.", 1, "geopolitics"),
    ("Litvinenko Assassination", "Real 2006 poisoning case implicating state-linked assassins in London.", 1, "geopolitics"),
    ("MH17 Shootdown Cover-Up", "Disputed 2014 downing of a airliner over Ukraine, with contested responsibility.", 1, "geopolitics"),
    ("Korean Air Lines Flight 007", "Real Cold War incident where a airliner was shot down, sparking cover-up claims.", 1, "geopolitics"),
    ("Kursk Submarine Disaster Cover-Up", "Claims Russian officials concealed the true cause of the 2000 sinking.", 1, "government"),
    ("Chappaquiddick Cover-Up", "Claim Ted Kennedy's 1969 accident involved a political cover-up.", 1, "history"),
    ("O.J. Simpson Frame-Up Theory", "Claim law enforcement fabricated evidence in the 1994 murder case.", 2, "crime"),
    ("Zodiac Killer Identity Cover-Up", "Claims investigators have long known but concealed the killer's identity.", 2, "crime"),
    ("JonBenét Ramsey Cover-Up", "Persistent claims of a deliberate cover-up in the unsolved 1996 case.", 2, "crime"),
    ("Jack the Ripper Royal Cover-Up", "Claim Victorian authorities shielded a royal-linked suspect.", 2, "crime"),
    ("Amelia Earhart Capture Theory", "Claim Earhart was captured by Japan and the truth was suppressed.", 2, "mystery"),
    ("Malaysia Airlines MH370 Hijack Theory", "Claim the 2014 disappearance involved a deliberate hijacking cover-up.", 1, "mystery"),
    ("Flight 800 Missile Theory", "Claim TWA Flight 800's 1996 crash was a missile strike, not mechanical failure.", 1, "mystery"),
    ("Concorde Crash Sabotage Theory", "Fringe claim the fatal 2000 Concorde crash involved deliberate sabotage.", 2, "mystery"),
    ("The Voynich Manuscript Hoax", "Debate over whether the untranslated medieval text is an elaborate hoax.", 3, "history"),
    ("Ancient Astronaut Nazca Lines", "Claim the Peruvian geoglyphs were markers for extraterrestrial visitors.", 3, "history"),
    ("Bermuda Triangle Government Cover-Up", "Extended claim authorities hide the true cause of Triangle disappearances.", 2, "mystery"),
    ("Antarctica Hidden Civilization", "Claim an advanced ancient civilization is buried under Antarctic ice.", 2, "history"),
    ("Global Elite Bloodline Theory", "Unfounded claim world leaders share a secret hereditary bloodline.", 2, "elite"),
    ("Council on Foreign Relations Control", "Claim the US think tank secretly dictates foreign policy.", 2, "politics"),
    ("Trilateral Commission World Control", "Claim the international policy group secretly coordinates global governance.", 2, "politics"),
    ("World Bank Debt Trap Conspiracy", "Claim international loans are deliberately structured to trap poor nations.", 2, "finance"),
    ("IMF Economic Sabotage", "Claim IMF policy prescriptions are designed to weaken borrower economies.", 2, "finance"),
    ("Central Banks Engineer Recessions", "Claim recessions are deliberately triggered to consolidate financial power.", 2, "finance"),
    ("Big Ag Seed Monopoly Conspiracy", "Claim agribusiness giants deliberately suppress seed diversity for control.", 2, "corporate"),
    ("GMO Health Cover-Up", "Unfounded claim regulators conceal health risks of genetically modified food.", 2, "health"),
    ("Aspartame Cancer Cover-Up", "Long-running unfounded claim regulators hid cancer risks of the sweetener.", 2, "health"),
    ("Water Fluoridation Cold War Origins", "Claim fluoridation began as a Cold War-era pacification experiment.", 2, "health"),
    ("Wireless Radiation Suppressed Studies", "Claim telecom industry buried research on cellphone radiation risk.", 2, "health"),
    ("Airline Contrail Health Studies Suppressed", "Extended chemtrail claim tying aviation lobbying to buried research.", 1, "environment"),
    ("Secret Space Program", "Claim a hidden, more advanced space program exists beyond public agencies.", 2, "space"),
    ("NASA Alien Contact Cover-Up", "Claim NASA has concealed evidence of extraterrestrial contact for decades.", 2, "ufo"),
    ("Disclosure Project Whistleblowers", "Claim numerous military/government witnesses have UFO evidence suppressed.", 2, "ufo"),
    ("Project Blue Book Cover-Up", "Claim the USAF's real UFO study findings were concealed from the public.", 1, "ufo"),
    ("Majestic 12 Documents", "Disputed alleged secret committee overseeing recovered UFO material.", 1, "ufo"),
    ("Nazi UFO Technology", "Claim Nazi Germany developed advanced flying-disc craft before WWII's end.", 2, "ufo"),
    ("Antarctic UFO Base", "Claim a hidden extraterrestrial or secret human base exists in Antarctica.", 1, "ufo"),
]

THEORIES = THEORIES + EXTRA
